-- Add migration script here
CREATE TABLE companies
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    varchar(255)
);

CREATE TABLE departments
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departments_name    varchar(255)
);

CREATE TABLE module
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255)
);

CREATE TABLE role
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255)
);

CREATE TABLE posts
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255)
);

CREATE TABLE users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(255),
    email varchar(255),
    phone varchar(255),
    male  integer,
    birth varchar(255),
    superior integer,
    post integer,
    company integer,
    joining_date VARCHAR(255),
    department integer,
    FOREIGN KEY (superior) REFERENCES users(id),
    FOREIGN KEY (post) REFERENCES posts(id),
    FOREIGN KEY (company) REFERENCES companies(id),
    FOREIGN KEY (department) REFERENCES departments(id)
);