[package]
name = "hrs_server_proc_macro"
version = "0.1.0"
edition = "2021"


[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
proc-macro = true
